name: Feature request
description: Suggest an idea for this project.
title: "[Feature]: "
body: 
  - type: checkboxes
    attributes:
      label: Mandatory confirmtion
      description: "By submitting this issue, you agree to:"
      options:
        - label: "follow this project's [Code of Conduct](https://github.com/sony/esstra/blob/main/CODE_OF_CONDUCT.md)."
          required: true
        - label: "follow this project's [Contributing Guidelines](https://github.com/sony/esstra/blob/main/CONTRIBUTING.md)."
          required: true
        - label: "have checked the [issue list](https://github.com/sony/esstra/issues), and confirm that a similar feature has not been requested before."
          required: true
  - type: textarea
    attributes:
      label: "Description"
      placeholder: "A clear and concise description of the feature you would like to see."
  - type: textarea
    attributes:
      label: "Background, motivation, etc."
      placeholder: "Background information or context explaining why this feature is needed. What problem does it solve?"
  - type: textarea
    attributes:
      label: "Expected results, benefits, etc."
      placeholder: "Clear and concise description of what you want to happen, what benefits will it bring to the users or this project."
  - type: textarea
    attributes:
      label: "Additional context"
      placeholder: "Add any other context or screenshots about the feature request here."
